http:
  port: "8081"

american:
  host: "training4-american-api-dharmesh.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  basepath: "/"
  client_id: "e3d39997a7da4c16969c9b559907272f"
  client_secret: "927F4DfC16ED42Ca96b3a4dd1A2De5dA"

training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"